services:
  postgres:
    image: postgres:16
    container_name: nest_postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .dev.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nest_api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .dev.env
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules 

volumes:
  postgres_data:
